parameters:
- name: cloud
  brief: Cloud
  kind: user
  parameters:
  - name: kind
    value: aws
  - name: region
    fromEnv: AWS_REGION

- name: dns
  brief: DNS
  kind: user
  parameters:
  - name: name
    brief: DNS name
    fromEnv: HUB_STACK_NAME
  # - name: baseDomain
  #   brief: DNS base domain
  #   fromEnv: BASE_DOMAIN
  #   default: devops.delivery
  - name: domain
    fromEnv: HUB_DOMAIN_NAME

- name: component.storage-class
  parameters:
  - name: name
    value: default
  - name: type
    value: gp2

- name: terraform.bucket
  brief: Terraform state location
  parameters:
  - name: name
    fromEnv: HUB_STATE_BUCKET
  - name: region
    fromEnv: HUB_STATE_REGION

- name: component.ingress
  parameters:
  - name: dashboard
    value: 'true'
  - name: ssoUrlPrefix
    value: apps
  - name: urlPrefix
    value: app

# - name: component.minio
#   kind: user
#   parameters:
#   - name: name
#     value: buckets
#   - name: namespace
#     value: ${component.kubeflow.namespace}
#   - name: accessKey
#     value: minio
#   - name: secretKey
#     value: minio123
#   - name: region
#     value: ${cloud.region}
#   - name: default.bucket.name
#     value: storage

- name: component.prometheus
  parameters:
  - name: prometheus.volumeSize
    value: 10Gi
  - name: prometheus.retention
    value: 12h

- name: component.external-dns.interval
  value: 1m

- name: component.dex
  parameters:
  - name: namespace
    value: kube-system
  - name: passwordDb.email
    brief: User email (to login with SSO)
    fromEnv: COMPONENT_DEX_PASSWORD_DB_EMAIL
  - name: passwordDb.password
    brief: User password (to login with SSO)
    fromEnv: COMPONENT_DEX_PASSWORD_DB_PASSWORD

- name: component.harbor
  parameters:
  - name: storage
    value: local
  - name: password
    brief: Password for user "admin" (Harbor)
    fromEnv: COMPONENT_HARBOR_PASSWORD

- name: component.postgresql
  parameters:
  - name: database
    value: postgres
  - name: user
    brief: Username for PostgreSQL database
    fromEnv: COMPONENT_POSTGRESQL_USER
  - name: password
    brief: Password for PostgreSQL database
    fromEnv: COMPONENT_POSTGRESQL_PASSWORD

- name: component.kubernetes-dashboard.rbac.kind
  value: admin
